## This is the voting app pod for end users

apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db
    app: demo-voting-app
spec:
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    name: db
    app: demo-voting-app