apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    name: voting-app-deployment
    app: demo-voting-app
spec:
  template:
    metadata:
      name: voting-app-pod
      labels:
        name: voting-app-pod
    spec:
      containers:
        - name: voting-app-container
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
  replicas: 3
  selector:
    name: voting-app-pod