apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    name: worker-app-deployment
    app: demo-voting-app
spec:
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: demo-voting-app
    spec:
      containers:
        - name: worker-app-container
          image: dockersamples/examplevotingapp_worker
  replicas: 1
  selector:
    name: worker-app-pod
    app: demo-voting-app